name: CI for commits

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup nodenv
        run: |
          git clone https://github.com/nodenv/nodenv.git ~/.nodenv
          git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build
          chmod +x ~/.nodenv/bin/nodenv
          export PATH="$HOME/.nodenv/bin:$PATH"
          which nodenv
          eval "$(nodenv init -)"
          eval "nodenv install $(cat .node-version)"
          eval "nodenv global $(cat .node-version)"
          echo "PATH=$HOME/.nodenv/bin:$PATH" >> $GITHUB_ENV
          echo "NODENV_ROOT=$HOME/.nodenv" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          NODENV_ROOT: ${{ env.NODENV_ROOT }}
        run: |
          npm install

      - name: Load environment variables
        run: |
          if [ "${{ matrix.environment }}" == "staging" ]; then
            cp .env.staging .env
          else
            cp .env.production .env
          fi
        shell: bash

      - name: Build App
        env:
          NODENV_ROOT: ${{ env.NODENV_ROOT }}
        run: |
          npm run build-production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.environment }}
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ matrix.environment }}
          path: ./dist

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: build-artifacts-${{ matrix.environment }}
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages
        with:
          token: ${{ secrets.DEPLOY_PAGES_TOKEN }}
          artifact_name: ${{ matrix.environment }}-gh-pages
