name: CI for commits

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup nodenv
        run: |
          git clone https://github.com/nodenv/nodenv.git ~/.nodenv
          git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build
          chmod +x ~/.nodenv/bin/nodenv
          export PATH="$HOME/.nodenv/bin:$PATH"
          which nodenv
          eval "$(nodenv init -)"
          eval "nodenv install $(cat .node-version)"
          eval "nodenv global $(cat .node-version)"
          echo "PATH=$HOME/.nodenv/bin:$PATH" >> $GITHUB_ENV
          echo 'eval "$(nodenv init -)"' >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          echo "Node version before npm install: $(node -v)"
          eval "$(nodenv init -)"
          echo "Node version before npm install: $(node -v)"
          npm install

      - name: Build App
        run: |
          echo "Node version: $(node -v)"
          npm run build-production

      - name: Serve Webpack
        run: npm serve
