name: CI for commits

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup nodenv
        run: |
          git clone https://github.com/nodenv/nodenv.git ~/.nodenv
          git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build
          chmod +x ~/.nodenv/bin/nodenv
          export PATH="$HOME/.nodenv/bin:$PATH"
          which nodenv
          eval "$(nodenv init -)"
          eval "nodenv install $(cat .node-version)"
          eval "nodenv global $(cat .node-version)"
          echo "PATH=$HOME/.nodenv/bin:$PATH" >> $GITHUB_ENV
          echo "NODENV_ROOT=$HOME/.nodenv" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          NODENV_ROOT: ${{ env.NODENV_ROOT }}
        run: |
          npm install

      - name: Build App
        env:
          NODENV_ROOT: ${{ env.NODENV_ROOT }}
        run: |
          npm run build-production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY }}

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git clone --depth=1 --branch=gh-pages git@github.com:${{ github.repository }} gh-pages
          rsync -av --delete ./dist/ gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
